### ISSUE TITLE
calendarize_news / "Object of class DateTime could not be converted to string"

### ISSUE THREAD

**Issue by mminyades** [lochmueller/calendarize#100]
In combination with "calendarize_news" the following error-message appears:

PHP Catchable Fatal Error: Object of class DateTime could not be converted to string in /html/typo3/typo3temp/Cache/Code/fluid_template/Calendarize_Calendar_partial_Month...

Error shows up in "year-view" and "month-view".

tested with:
calendarize 2.4.1
calendarize_news 1.3.1
news 5.2.0

**Comment by lochmueller** [comment]
Thanks for the report. calendarize_news use a old Month partial. Fixed in this commit https://github.com/lochmueller/calendarize_news/commit/f767a889f022c207dacc29a713099144de6879df and also update the extension. Version 2.0.0 is out now... https://packagist.org/packages/lochmueller/calendarize-news#2.0.0
