### ISSUE TITLE
Multi language support for events broken in 2.6.1

### ISSUE THREAD

**Issue by lentizz** [lochmueller/calendarize#114]
I have a multi language website and the localization for events worked fine. Since i updated to 2.6.1 i can localize an event, but the "Date Option" doesn't show the event in the second language anymore. Neither can i set a new date (new event) for the localized record.
For older records which were translated already, it just says: "There is 1 record in the index ..." but i cannot change the date since i can't see it ...
It might just be a TCA problem?
Can you reproduce this behaviour or am i the only one with the problem?

**Comment by lochmueller** [comment]
This is the related line:
https://github.com/lochmueller/calendarize/blob/dc6c194f882dc9daa289660f837d7aa2377f47e2/Classes/Register.php#L43
... and this the related patch: https://github.com/lochmueller/calendarize/commit/802947fb3b87a3d14228cc9ad77ef5987234cdfa#diff-5493e20367b495733fd0e1cb9a37c43c

If you want to create real "translation" you do not need the calendarize configuration in the overlay, because there are no translatable fields in the calendarize configuration (only structured information, that are independent of the language).

Regards,
Tim
