### ISSUE TITLE
dates are shifted in detail view

### ISSUE THREAD

**Issue by netthinks** [lochmueller/calendarize#121]
In detail view, a date is not displayed correct. The start date and end date are shifted by one day:
![07-12-_2016_11-19-56](https://cloud.githubusercontent.com/assets/23073131/20963850/6fd72ee4-bc6f-11e6-948c-cd522628aa82.jpg)
TYPO3 7.6, latest calendarize (master)

**Comment by lochmueller** [comment]
I cannot rebuild this on my dev machine. Seems to be also a timezone problem... I will check this in a few days.

**Comment by lochmueller** [comment]
@netthinks Do you have some more information about timezone settings on your machine?

**Comment by netthinks** [comment]
date/time support 	enabled
"Olson" Timezone Database Version 	2016.8
Timezone Database 	internal
Default timezone 	Europe/Berlin
Directive	Local Value	Master Value
date.default_latitude	31.7667	31.7667
date.default_longitude	35.2333	35.2333
date.sunrise_zenith	90.583333	90.583333
date.sunset_zenith	90.583333	90.583333
date.timezone	Europe/Berlin	Europe/Berlin

**Comment by lochmueller** [comment]
Hey @netthinks 
I cannot rebuild this issue. I changed my timezone also from UTC to Berlin and create a allday event and run test with the different views (also incl. moment.js and excl. momentjs.). But everything works well. Sorry... now it is your part to run some more debugging in your envoriment. I cannot help at the moment. I close this issue here. Please check the current master for further check, because there are some fixes (release of version 3.0.0 in the next days)
Regards,
Tim
