### ISSUE TITLE
category selection

### ISSUE THREAD

**Issue by stephangrass** [lochmueller/calendarize#13]
Hi,
in an previous issue you wrote: "The category selection (example with the default Event Model) is part of the next release...". Do you meen, that calendarize will use the TYPO3 categories to limit the event list. I think, this is very useful, especially for calendarize_news. 

By the way: I love your extension
Stephan

**Comment by lochmueller** [comment]
Hey Stephan,

thanks for the feedback. In the current version the categories of the core are used:
https://github.com/lochmueller/calendarize/blob/master/ext_tables.php#L18

calendarize_news is just a "connection" extension to connect news with calendarize. So no additional features/fields are added... But you are right. A category selection of the existing categories (to reduce the amount of events) is usefull... Feel free to create a feature request for this extension: https://github.com/lochmueller/calendarize_news

Should we close this issue here?

Regards,
Tim

**Comment by stephangrass** [comment]
OK.
