### ISSUE TITLE
Indexer frequencyLimitPerItem settings

### ISSUE THREAD

**Issue by saneinsane** [lochmueller/calendarize#146]
Currently the frequencyLimitPerItem works beginning with the start date. If the start date is long ago, no future index entries will be created. I wanted to limit the future entries count and reduced frequencyLimitPerItem to 4, but now weekly events with a start date more than 4 weeks ago aren’t indexed anymore.
It would be cool to
a) create the next [frequencyLimitPerItem] index entries in the future **OR**
b) set a relative time limit for the entries that should be created (create all index entries for -1 month  till +3 months from today).
What do you think?
Rainer

**Comment by lochmueller** [comment]
Hey Rainer,
a) is not possible, because there is no "single index" process. If you run e.g. the scheduler task the current date is every time another (now!).
b) This is the better option and easy to integrate. It is part of the TimeTimeTable incl. Frequency & Recurrence. Futhermore we need the both fields in the configuration record...

Regards,
Tim

**Comment by lochmueller** [comment]
Hmm... this is a very old issue. I close this one, because there was no progress in the last two years... Sorry :-/
