### ISSUE TITLE
f:format.date in german

### ISSUE THREAD

**Issue by blueamerican** [lochmueller/calendarize#293]
I want to have a date in german:
{index.startDate -> f:format.date(format: 'l, d. F')}

Therefore i set the TS:

config {
   language = de
   locale_all = de_DE.UTF-8
  sys_language_uid = 0
}

locale_all is correct. But i only get:
Thursday, 21. February

What is wrong?

**Comment by lochmueller** [comment]
Hey @blueamerican ,
The "f:date.format"-ViewHelper use a DateTime->format in default and strftime, if your format catains at least one `%` char. DateTime->format do not repect the locale (php.net documentation), so the solution is, to use a strftime format: https://php.net/manual/function.strftime.php
So please try `%A, %e. %B`

I close this issue, because it is not related to calendarize itself.

Regards,
Tim

**Comment by blueamerican** [comment]
thx, this works.
