### ISSUE TITLE
error when switching language

### ISSUE THREAD

**Issue by marcelbirrer** [lochmueller/calendarize#314]
site with two languages, german and french. calendarize records has been localized to french. if a user switches the language on a detail page, following error occurs:

**trim() expects parameter 1 to be string, null given**

Core: Exception handler (WEB): Uncaught TYPO3 Exception: trim() expects parameter 1 to be string, null given \| TypeError thrown in file /home/sgar-ssar.ch/ftp/www/typo3conf/ext/calendarize/Classes/ViewHelpers/TitleTagViewHelper.php in line 33. Requested URL: https://sgar-ssar.ch/fr/cours-congres/calendrier-des-congres/event/?tx_calendarize_calendar%5Bindex%5D=884&cHash=a7cc86f83d34539ffca7530cad680793

**Comment by lochmueller** [comment]
Hey @marcelbirrer ,
already fixed in current master and also version: https://github.com/lochmueller/calendarize/blob/master/Classes/ViewHelpers/TitleTagViewHelper.php#L33
https://github.com/lochmueller/calendarize/commit/4499a56c02cbb345df181be83beb021c9891a019

Please upgrade to Version > 4.2.0.

Regards,
Tim

**Comment by marcelbirrer** [comment]
you're right, it works! thanks!
