### ISSUE TITLE
Default Ordering in Backend Module

### ISSUE THREAD

**Issue by FraeuleinWi** [lochmueller/calendarize#343]
We migrated from cal extension to calendarize and love it! This is our pilot project for testing the extension and we plan to use it for several more setups.

Only issue we found so far is that the default ordering for the backend module view is set to ASC, which might be okay if it is only a few events that are imported, but we are talking about more than 3000 events at the moment. Other sites with even more events are planned.

So it would be nice to have the **events sorted in a descending order by default or to be able to change the sorting via extension options**.

I know how to change defaultOrdering in the Repository, but I would like to keep the extension updateable without having to change the Repository manually after an update. We use custom extensions to do so, i.e. overriding certain things like templates, but overriding Repository, Controller and ext_localconf.php would be a lot of effort for a tiny change. And the possibility that we'd have to change the custom extension after an update is probably high.

So I'm trying my luck here, since I guess there may be even more users who might enjoy sorting options in the backend.

Thanks a lot in advance :)

P.S.: I would also be able to contribute to this extension, by developing a default orderings setting option, if desired ;)

**Comment by lochmueller** [comment]
Hey @FraeuleinWi ,
thanks for your feedback. There are already preperations in the extension for supporting a "option form" on top of the backend list for sorting and filter options:
https://github.com/lochmueller/calendarize/blob/master/Classes/Controller/BackendController.php#L53
https://github.com/lochmueller/calendarize/blob/master/Resources/Private/Templates/Backend/List.html#L13

Feel free to use this (enable it and add the sorting direction).
Otherwise I will check this in the next weeks...

Regards,
Tim

**Comment by lochmueller** [comment]
Hey @FraeuleinWi 
Sorting direction will be part of the next release.
Regards,
Tim
