### ISSUE TITLE
ICS-Import doesn't work

### ISSUE THREAD

**Issue by rudolfweber** [lochmueller/calendarize#366]
The task I created doesn't import any event.
Here are the links to my ICS-file and to a screenshot of the Typo3-message : 
https://www.regino-gym.de/kalender/regino.ics
https://www.regino-gym.de/kalender/kalenderfehler.png

**Comment by lochmueller** [comment]
Hey @rudolfweber 
I streamline the import process with the last commit. Two problems are still open:

First the DB field is not "ready" for events after > 2042 (do not now the excact date, but will be something like "end of integer"). This result in the error of `2: SQL error: 'Out of range value for column 'start_date' at row 1'`. This error also visible without ICS import, if your create a event in this year manually, the error is also thrown in the backend. In this case, we have to change the DB definition of the index table (could only be done in a major release).

Secondly, the current ICS import do not handle the event before 1970. The event is ignored. There is also a better implementation (only in composer mode) https://github.com/lochmueller/calendarize/blob/master/Classes/Service/IcsReaderService.php#L31 but not finished yet. I suggest to work on the new implementation, because the integration is more valid (RFC conform): https://github.com/lochmueller/calendarize/blob/master/Classes/Service/IcsReaderService.php#L106

Thanks for report the problem... Are you just t he reporter or it is also possible to get some ideas/work from you? ;) 

Regards,
Tim

**Comment by Raymondsnijders** [comment]
Is it possible to update existing records during the import? Now I get constantly duplicates.

**Comment by lochmueller** [comment]
With the current intergation it is a "Migration assitent" so no update is possible/needed. Just truncate the calendarize tables and executre the task again.

**Comment by Raymondsnijders** [comment]
Hi Tim,

Thanks for your quick response. I run every the import task for the same calendar. So where do I set to truncate the table?

**Comment by lochmueller** [comment]
Hmm... sorry. My answer was for the wrong component. You are right... but I think this problem is already fixed in current master. If not, feel free to create a new issue 👍

**Comment by lochmueller** [comment]
Hey @rudolfweber 
I handle this problems, by changing the DB field type to a real date field. Now there are also dates before 1970 and after 2042 possible. There is no migration at the moment. If you found more errors, please create new issues...
Regards,
Tim
