### ISSUE TITLE
Rename Backend Description Date

### ISSUE THREAD

**Issue by ohm-meter** [lochmueller/calendarize#445]
Hi,

We thought that we had a Bug in the List view because Event with old date was shown, but it was an missunderstanding.
Because we add an End Date to an Event. After Searching some hours we found that is a Feature 👍 

So i think it is good to rename the Backend Field "Date" to "Date and duration of an Event" and "Start date" to "Start Date of the Event" and "End Date (optionally)" "End Date of the Event (duration, optionally)" or something else.

In German i would write: "Veranstaltungs Datum und dauer", "Startdatum des Events" , "Optional: Endatum des gesamten Events", "Dynamisches Event Länge"
![Caritas_Submarken__Live___TYPO3_CMS_10_4_8_](https://user-images.githubusercontent.com/49782166/96092756-97088500-0ecb-11eb-99d5-a746e202f383.jpg)

Cheers Oliver

**Comment by lochmueller** [comment]
Hey @ohm-meter 
Thanks for the hit... I will check this and change it. I try to not add „Event“ or „Veranstalltung“ because the configuration must not always be part of an “event“. I will add more speaking labels...
Regards,
Tim

**Comment by ohm-meter** [comment]
Thanks, i understand what you mean :) I think a clearer description will help a lot

**Comment by lochmueller** [comment]
I added the "duration" to the enddate and change the headline to "Date and duration". If you have better labels, feel free to send pull requests (keep in mind, that the configuration is for "events", but also for "pages" etc. So I suggest not using "event" in the labels). 
Otherwise it would be helpfull to explain, what you think will you fill out the fields wrong?! Do you have a recurrence event and enter the last day of the series?

I close this issue...
