### ISSUE TITLE
CalMigrationUpdate.php incorrectly formats start_date and end_date, causing most events to be converted incorrectly

### ISSUE THREAD

**Issue by Abdull** [lochmueller/calendarize#453]
Using 
* calenderize 7.1.0
* TYPO3 10.4.9
* PHP 7.4.10
* MariaDB 10.1.45

`CalMigrationUpdate.php` incorrectly formats `start_date` and `end_date`, causing most `cal` events to be migrated to `calendarize` events with `start_date = 0000-00-00` and `end_date = 0000-00-00`.

This in turn causes most migrated calendarize events to be ignored when reindexing calendarize events.

In few cases, a `cal` event's `start_date` and `end_date` gets converted to an `calendarize` event with `start_date` and `end_date` different from  0000-00-00, but it's a wrong date nevertheless.

Examples:
* A `cal` event with `start_time = (int) 20171027` gets converted to a `calendarize` event with `start_time = (date) 0000-00-00`
* A `cal` event with `start_time = (int) 20171109` gets converted to a `calendarize` event with `start_time = (date) 2015-10-18`

**Comment by Abdull** [comment]
One solution is to not change `cal`'s date format at all, e.g. change [the current `migrateDate(..)` function](https://github.com/lochmueller/calendarize/blob/def0e655d4d2c626e076a4d7c586c01849048c4c/Classes/Updates/CalMigrationUpdate.php#L976) to:

```
protected function migrateDate($oldFormat)
  {
    return $oldFormat;
  }
```

**Comment by wazum** [comment]
Can't confirm that, I migrated > 5000 records and the date columns are set to the correct date or NULL

**Comment by okmiim** [comment]
@Abdull I doupt, that you run the wizard at the versions mentioned.

However this error happens in calendarize 6.0.0 (assumption).
This is due the breaking change form **timestamps to "real date"** (0db3fc886fe21c763aae7b17081073d5ac1a251c).

@lochmueller Maybe a bugfix version 6.0.1 would be useful here. `cal` does not seem to be activly supported anymore, so people start migrate to this extension. These people probaly will use the latest version both extensions supported (typo3 v9.5).

@lochmueller I think the CalMigrationUpdate is in the current version is dead code, because `updateNecessary` always return false and it will never show up. In addition to that the extension cal does not support typo3 v10 and seems not to be actively developed. So I suggest to remove the wizard.

@wazum At which calendarize version did you migrate? It should be before 6.0.0 / before running the DateFieldUpdate wizard.

**Comment by wazum** [comment]
@okmiim 
Update from calendarize "^3" to version to 7.2 (TYPO3 CMS 10.4)

**Comment by okmiim** [comment]
@wazum
It sounds like you just updated from an old version and used the "Calendarize Date Field" (DateFieldUpdate.php) wizard.
However this issue is about the migration from [Calendar Base](https://extensions.typo3.org/extension/cal/) (short `cal`), which is a **different** extension.

**Comment by lochmueller** [comment]
@okmiim for the wizard. If there is a v10 cal version in the feature, I will reenable the wizard.

@okmiim For the 6.0.1: Sorry, but there will be no new versions for old releases. I have many extensions to maintain and if there are problems in the old versions, feel free to fork and install the package from your repository. This is the only way to keep the space with the upcomming core versions and dependencies.
