### ISSUE TITLE
CalMigrationUpdate.php uses outdated Migration wizard API

### ISSUE THREAD

**Issue by Abdull** [lochmueller/calendarize#454]
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.5/Deprecation-86366-MethodsInAbstractUpdate.html
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.4/Feature-86076-NewAPIForUpgradeWizards.html

AbstractUpdate's methods signatures don't work in modern environments anymore: The method signatures don't have parameters, this in turn causes a call such as [`$this->performSysCategoryUpdate($calIds, $dbQueries, $customMessages)`](https://github.com/lochmueller/calendarize/blob/def0e655d4d2c626e076a4d7c586c01849048c4c/Classes/Updates/CalMigrationUpdate.php#L106) to throw an exception because `performSysCategoryUpdate($calIds, array &$dbQueries, &$customMessages)` expects an array as second parameter, but gets `null` as parameter.

**Comment by lochmueller** [comment]
Hey @Abdull 
I think you are using a old version. The AbstractUpdate is gone since the TYPO3 v10 migration: https://github.com/lochmueller/calendarize/commit/7e218146497049ee8b8600442c52f2c2818aa6c0#diff-3a81d6ad1a7ed9ddd582713f4e09ac726dc05a28eae543996836defd3254a9f0
The wizards use the new `UpgradeWizardInterface`.
Regards,
Tim
