### ISSUE TITLE
Migrating events from EXT:cal

### ISSUE THREAD

**Issue by osw-mw** [lochmueller/calendarize#476]
I had problems migrating events with version 6.0.0. 

With the attached patches I made it working.

[Slots-CalMigration.patch.txt](https://github.com/lochmueller/calendarize/files/5703482/Slots-CalMigration.patch.txt)
[Updates-CalMigrationUpdate.patch.txt](https://github.com/lochmueller/calendarize/files/5703483/Updates-CalMigrationUpdate.patch.txt)

**Comment by okmiim** [comment]
That is correct. This is similar to #453 .

**Comment by osw-mw** [comment]
Yes, #453 is one of the issues that I found (but not the only one).

**Comment by lochmueller** [comment]
Hey @osw-mw 
I checked the patches and merged a few parts to the current master. Next time, feel free to fork the repository and add your changes based on the current master via pull request. It is much easier to work with the changes instead of text files. There will be no new versions for old releases. 
Thank you.
Regards,
Tim
