### ISSUE TITLE
cal migration wizard writes source in sys_category.import_id not sys_category.import_source

### ISSUE THREAD

**Issue by sypets** [lochmueller/calendarize#493]
There is an explicit field for the source in sys_category (import_source), but the migration wizard writes the source to import_id and uses a prefix. (It is a bit messy that the import_id field in sys_category is a VARCHAR and not an int in the first place, I assume the import_source was added later).

It might also be nice to do this in the same way, for example in tx_calendarize_domain_model_event.import_id (add import_source and change to int).

See existing records from news import.

```
select uid,title,import_id,import_source from sys_category where import_id != '' and not deleted and not hidden;
+-----+-------------------------------------------------------------+-----------+-------------------------+
| uid | title                                                       | import_id | import_source           |
+-----+-------------------------------------------------------------+-----------+-------------------------+
|  45 | Top-Thema                                                   | 2         | TT_NEWS_CATEGORY_IMPORT |
|  46 | Weitere Meldungen                                           | 4         | TT_NEWS_CATEGORY_IMPORT |
```

**Comment by lochmueller** [comment]
Hey @sypets 
thanks for the note. I will keep the current structure (just import ID as string), because ical use also String as identifier and the fields are primary for import the ical (ICS) structures. But I checked the fields and it is totally wrong that some fields are "TEXT". So I moved the field to a trait and use it in all the models. So the type will be "varchar(100) DEFAULT NULL" in the next major release.
Regards,
Tim
