### ISSUE TITLE
ics file contains encoded html tags in description

### ISSUE THREAD

**Issue by artus70** [lochmueller/calendarize#521]
The html tags inside event detail information are erroneously encoded:

`&lt;p&gt;Detail text block.&lt;/p&gt;`

![grafik](https://user-images.githubusercontent.com/367315/112125060-507a2d80-8bc3-11eb-9bf1-55627a3ad80d.png)

TYPO3 10.4.14, calendarize 8.2.0

**Comment by okmiim** [comment]
Hi @artus70,

Could you check if you used a custom template (e.g. if you copied all partials in an older version) for [Partials/Feed/Item.ics](https://github.com/lochmueller/calendarize/blob/e8fcfc07abd015d303385d87b99379c8aadc091e/Resources/Private/Partials/Feed/Item.ics)?

If not, could you provide the html source of the description field and the source of the resulting ics file?

**Comment by artus70** [comment]
Man, you are right. 

The goal is to convert the description to pure ASCII, right? (BTW, could be questioned.)

I have now updated it and checked it again: At the moment, occurrences of `&nbsp;` still remain in the text.

**Comment by okmiim** [comment]
The encoded html entities should be removed by adding `-> f:format.htmlentitiesDecode()` (not tested yet).

Yes, my idea is to keep the `DESCRIPTION` without html, since it is supported everywhere.
A html description might be better suited in `X-ALT-DESC`. This is not 'standardized' by a RFC, however commonly used (e.g. Outlook).
On the other side e.g. Google Calendar puts html formatting directly into `DESCRIPTION`.

I will tackle these changes soon.
