### ISSUE TITLE
Revert change of upgrade wizard identifers?

### ISSUE THREAD

**Issue by sypets** [lochmueller/calendarize#531]
I have done some more thinking and I don't think it is a good idea to change existing upgrade wizard identifers as done in PR #498.

As a pro, it is a hassle to call the wizards in command line with the fully qualified class name and quoting.

But as a con, changing wizards that already ran is not such a good idea - the wizards are already marked as done in the registry (sys_registry), now they will be (unnecessarily) checked every time the upgrade wizard card is opened. (this also is done on new installations and installations where the wizard does not apply, but I guess that can't be helped).

Perhaps, as an alternative we can document how to run the upgrade wizards on the command line?

What do you think? @lochmueller 

See also discussion about naming conventions for upgrade wizard identifers, https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1334 where it was also poined out existing identifiers should not get changed (in the core).

**Comment by lochmueller** [comment]
Hey @sypets ,
I would keep the current identifier in the extension.
Every wizard has a "updateNecessary" method, that check if the wizard need to be execute. I think in your case it is the EXT:cal migration wizard. This is displayed because "tx_cal_event" still exists. If "tx_cal_event" is gone the wizard also should disappear.
Regards,
Tim
