### ISSUE TITLE
Module view: Hide events or groups which are read-only

### ISSUE THREAD

**Issue by artus70** [lochmueller/calendarize#538]
We provide some general calendar information like common holidays which can be used by our users to use as exclude dates/ranges from some event series. 

These event groups are read-only for the users, but still appear in Web->Calendarize as if they were editable. When clicked, an error message concerning missing access rights is shown. This is confusing and unnecessary.

I suggest that such read-only event groups be hidden there.

**Comment by lochmueller** [comment]
Good point. Or also listed but without edit options...

**Comment by lochmueller** [comment]
![Bildschirmfoto 2021-08-04 um 00 45 05](https://user-images.githubusercontent.com/3907126/128095896-2e40f5c7-35f8-49e2-b158-c39f2f83cc80.png)

There will be a new type selection in the next release. Since the backend selection is stored in the backend user, the user can select the right type and it will be always preselected.
