### ISSUE TITLE
Filter events by categories

### ISSUE THREAD

**Issue by Hobokens** [lochmueller/calendarize#54]
Hi,
sorry, one more question: I use the newest calendarize from github with TPO3 7.6.4 and try to filter events in list view by categories
In the file '...\layout\default.html' I added without success:
```
<f:for each="{event.categories}" as="category">
	<f:if condition="{category.uid} == 3">
		<div class="calendarize">
			<f:render section="Main" />
		</div>
	</f:if>
</f:for>
```
Regards
Tom

**Comment by lochmueller** [comment]
Hey Tom,
your cahnge do not work because the Layout will be used by multiple and also single event. Why you reduce the selection of categories in the configuration of the plugins? YOu can select the category in the "Categories" Tab of you plugin element.

Does this solve the problem...?

Regards,
Tim

**Comment by Hobokens** [comment]
Hi Tim,

oh my god, I'm stupid. I didn't know that it is so easy.

Thanks!
Tom

**Comment by lochmueller** [comment]
Nice... if this is a commercial project, I am always happy about same financial support, to get all planed features on the way ;)
