### ISSUE TITLE
ICS - not working for mobile androide device google calendar

### ISSUE THREAD

**Issue by ClaudiaK21** [lochmueller/calendarize#548]
When I try to download a single event on my smartphone and "open with" google calendar, it won't.
Is it somehow possible?

I noticed 
- when opening the ics file with a texteditor that there is an **empty line** befor End:VCALENDER  
- and all the event body text is shown under DESCRIPTION:
  Is it possible to only include the teaser text for the description?

**Comment by lochmueller** [comment]
Hey @ClaudiaK21 ,
could you download the ICS, change to two points, upload it manually and check, if this solve the problem on your smartphone. Then we know, that these are the problems. Or could you download the "not working" ICS and upload it to this issue here?!
Regards,
Tim

**Comment by ClaudiaK21** [comment]
I can upload this ics, I don't know what you meant with "change to two points, upload it manually and check".
Thanks in advance for your help ;-)
[calendar.ics-ClaudiaK21.zip](https://github.com/lochmueller/calendarize/files/6421044/calendar.ics-ClaudiaK21.zip)

**Comment by lochmueller** [comment]
`I don't know what you meant` -> Remove the empy line, reduce the text, upload the file to your webserver and call the URL from your smartphone. It is also possible that your webserver send wrong headers for ICS files.

I think the "long text" is the problem. Which EXT:calendarize & TYPO3 version do you use?

**Comment by ClaudiaK21** [comment]
Ah yes, that proceedure I have already done. 
Remove the empy line, reduce the text, but then I could not open it with the google calendar, only with the native default calendar app of my smartphone.

**Comment by ClaudiaK21** [comment]
> Which EXT:calendarize & TYPO3 version do you use?

Typo3 9.5.26
calendarize 6.0.0

**Comment by lochmueller** [comment]
Hey @ClaudiaK21 ,

the EXT:calendarize version is very old. It is already fixed in the current versions:

https://github.com/lochmueller/calendarize/blob/master/Resources/Private/Layouts/Feed.ics
https://github.com/lochmueller/calendarize/blob/6.0.0/Resources/Private/Layouts/Feed.ics (your version)

https://github.com/lochmueller/calendarize/blob/master/Resources/Private/Partials/Feed/Item.ics
https://github.com/lochmueller/calendarize/blob/6.0.0/Resources/Private/Partials/Feed/Item.ics (your version)

There are several ViewHelpers that handle this. Please upgrade your versions or migrate the ViewHelpers/Templates by yourself.
I will close this issue.

Thank you,
Tim

**Comment by ClaudiaK21** [comment]
Sorry to have another question:
Unfortunately we cannot update calendarize to version 10, because 6.0.0 is the last one compatible for typo3  **9.5.**?
At least I understand it this way it is shown on  https://extensions.typo3.org/extension/calendarize

It is not possible to just migrate the ViewHelpers/Templates, we have tried, but it does not work.
Just to make sure, that means, unless we update typo3 to version 10 and then calendarize - there is no way to get this work?

**Comment by lochmueller** [comment]
Hey @ClaudiaK21 
the ViewHelper could be migrated to old TYPO3 versions (I don't know if copy&paste is enough). There will be no free support for old TYPO3 versions of the extension. Sorry.
Regards,
Tim
