### ISSUE TITLE
Faceted Search (ke_search) Indexer is not working

### ISSUE THREAD

**Issue by Schweriner** [lochmueller/calendarize#57]
Hello,

the default Indexer is not working for my extension records. It does not return any records from the database for multiple reasons:

KeSearchIndexer.php Line 55:
`$indexRepository->setOverridePageIds(GeneralUtility::intExplode(',', $indexerConfig['storagepid']));`

The field name of the storagePid in the Indexer Config is named "sysfolder". So the line should be:

`$indexRepository->setOverridePageIds(GeneralUtility::intExplode(',', $indexerConfig['sysfolder']));`

Then Repository still won't return any records of my Extension. My records using Calendarize got the uniqueRegisterKey "TgmEvents". When calling the IndexRepository on line 56, the Respository has never been informed which records should be returned so I have to add the following line in the KeSearchIndexer.php before:

`$indexRepository->setIndexTypes(array('TgmEvents'));`

This should be configurable in the indexer config of course.

But then: Still no records. The function getDefaultConstraints of the Repository add's my record to the query with this line:
`$constraints[] = $query->in('uniqueRegisterKey', $this->indexTypes);`

For any reasons: This is not working. Heres where I had to stop my research. I only can say using "equals" instead of "in" solves the problem herer.

Greetings from Schwerin, Germany and thanks for the extensions.

**Comment by lochmueller** [comment]
Hey @Schweriner 

thanks for your feedback. I Add this line to remove the problem, that there are no valid indexTypes: https://github.com/lochmueller/calendarize/commit/fdcf129b7fd6b11ae8d4fe8bf0ee57bed7467323
Change the "in" to "equals" is not the right solution, because you can select two types at the same time.

I will check the EXT:calendarize in the next days:
- switch "storagepid" to "sysfolder"
- configurable indexTypes via ke_search configuration

Please be patient because I am not using ke_search at all, so I have to build same test cases...

Regards,
Tim

**Comment by Schweriner** [comment]
Hello,

of course changing it into "equals" is not a correct solution. Just wondering why "in" is not working for me...

No stress. Thank you.
