### ISSUE TITLE
Feature: routeEnhancer support for pagination

### ISSUE THREAD

**Issue by phvt** [lochmueller/calendarize#570]
I'm taking a look into adding support for nice URLs with pagination, although hitting the [limit of 10000 static and countable mappers](https://github.com/TYPO3/TYPO3.CMS/blob/7aad9f6dea9246a1cc64f1b076e106605db3e04c/typo3/sysext/core/Classes/Routing/PageRouter.php#L567) gets more difficult to avoid.

**Comment by lochmueller** [comment]
Hey @phvt 
I added a general configuration to the extension as example. 10.000 pages is a huge amount of data. If you reach this with "itemsPerPage" = 10 (you have 100.000 dates in the list) I suggest to increase the "itemsPerPage" in the first step (the range of the other mappers is very small). Otherwise, we have to check for another solution. Any ideas? Feel free to test the setup or add some more technical information. Currently, I will close this issue.
Thank you,
Tim
