### ISSUE TITLE
Really compatible to TYPO3 8 LTS?

### ISSUE THREAD

**Issue by mbrodala** [lochmueller/calendarize#67]
The `ext_emconf.php` currently says this:

```php
    'constraints'      => [
        'depends' => [
            'typo3'      => '6.2.0-8.99.99',
            'php'        => '5.5.0-0.0.0',
            'autoloader' => '2.0.0-0.0.0',
        ],
    ],
```

While this certainly would be neat I don't expect this extension to be compatible with all current and future breaking changes until TYPO3 8 LTS is released. This should be toned down to `7.6.99`.

**Comment by lochmueller** [comment]
Hey @mbrodala 

I set this to 8.99.99 because the extension is actually 8.0.0 compatible and I check the extension against new releases. I do not want to release a new extension version, after each core sprint. So I think this is the best solution and developer can also use (and also test) the extension in the current release.

Futhermore the TER upload check the uploaded extension versions. The major version can not be larger than the current released version (so far so good!). Perhaps the TER uploader should check the minor part also, if version like 8.99.99 are not best practise?

Regards,
Tim

**Comment by mbrodala** [comment]
@lochmueller I get what you mean but currently this is a false promise. Where the current version is marked to be compatible with TYPO3 8 LTS, a sprint release in between can break this promise and you cannot change what has already been released on your site.

Releasing a new version after every sprint is actually the way to go from my POV since that clearly conveys the message that you actively check for compatibility.

Not sure about the TER upload check.

**Comment by lochmueller** [comment]
Hmm... I will change this in the next release ;)

**Comment by mbrodala** [comment]
Thanks for your understanding. :-)
