### ISSUE TITLE
PHP Warning: file_exists(): open_basedir restriction in effect

### ISSUE THREAD

**Issue by epx-anpf** [lochmueller/calendarize#695]
Hi,

i have a very similar issue like #604.

But i have another environment:
- PHP: 7.4.30
- Typo3: 9.5.36
- calendarize: 6.0.0
- composer: no

All the behavious is exactly the same like in the mentioned ticket.

If i change in ext_tables.php line 70

```php
$iconPath = \TYPO3\CMS\Core\Utility\PathUtility::getAbsoluteWebPath(
    \TYPO3\CMS\Core\Utility\GeneralUtility::getFileAbsFileName('EXT:calendarize/Resources/Public/Icons/')
);
```

to

```php
$iconPath = 'EXT:calendarize/Resources/Public/Icons/';
```

it works for me. I know this version is kind of old but the client has an elts. Is there a chance to fix this?

Greetings Andreas

**Comment by lochmueller** [comment]
Hey @epx-anpf 

Sorry, but EXT:calendarize 6.0.0 is older than 2 years and there are many versions with hundreds of fixes between 6.x and the current main branch. We could not handle multiple versions or something like ELTS, because we do this in our free time and mostly without getting money :-/ 

So I will close this issue and I suggest updating to more current versions (PHP 7.4 is also nearly EOL). Had it been a composer installation, then I would suggest forking the project and install the extension from this fork. In your case, the easiest (not the best way) is just changing this line directly in the extension.

Regards,
Tim
