### ISSUE TITLE
List view shows all Events of the day eve they are already over

### ISSUE THREAD

**Issue by shortyxs** [lochmueller/calendarize#696]
As the title says it: In the list view I have all scheduled events for the day, even those that are in the past already.
I'd like to have only eventy that are currently running or will start later today.

I did not find any option to set this up?

**Comment by lochmueller** [comment]
Hey @shortyxs 
You can change this TS constant to "now": https://github.com/lochmueller/calendarize/blob/master/Configuration/TypoScript/constants.typoscript#L25
This should fit your requirement.
Regards,
Tim

**Comment by shortyxs** [comment]
It does not seem to work.
I already hat the list view set to "now" as the relative start date and "today" as the relative end date.

I added `plugin.tx_calendarize.settings.listStartTime = now` But it does not change anything in the behavior.

**Comment by lochmueller** [comment]
OK. Sounds like some misconfiguration. Please add your TYPO3 Version, Extension Version and composer yes/no. I will check this in the next days/weeks.

Regards,
Tim

**Comment by okmiim** [comment]
Hi @shortyxs,
Please check in the extension manager the option `Respect times in time frame constraints`, enable it and test it again.

https://github.com/lochmueller/calendarize/blob/0b4aea89c1d20b6f633f824a92f85cfdb769e90e/ext_conf_template.txt#L19-L20

**Comment by okmiim** [comment]
Hi @shortyxs,

the option `Respect times in time frame constraints` can be found under `Admin Tools > Settings > Extension Configuration`.
In the default configuration, list views only check the start/end date and **NOT** the start/end time, since this gives a better performance. When the option is enabled, also the time is respected.

I have added some reference documentation in 47ddeda137237cbd65d3308198e6ceed55d3767c and can be seen in [DOCS > Extension Configuration](https://docs.typo3.org/p/lochmueller/calendarize/main/en-us/Reference/ExtensionConfiguration/Index.html#respect-times-in-time-frame-constraints-respecttimesintimeframeconstraints).

---
`useRelativeDate` is referring to the plugin configuration (list view) and should not be confused with dynamic dates of events.

Here is one example (in this case the `now` is also the _default value_):
![Example plugin configuration with useRelativeDate set, from now to +1 week](https://user-images.githubusercontent.com/7593443/177056041-e49f41fc-0844-4827-bcdc-e37a57cb133c.png)

**Comment by lochmueller** [comment]
Thanks for the details @okmiim .
I will close this issue.
