### ISSUE TITLE
Show current month events on list mode when navigating through years

### ISSUE THREAD

**Issue by GeorgeTodea** [lochmueller/calendarize#723]
Hi,

I am using the mode List only for showing the events of current month. 

Below this, I am also using same plugin with mode Year. When I am using the button to go to 2021, I dont have any events (as it should be, as only 2022 events are at the moment in database). But when going back to 2022 (tx_calendarize_calendar[action]=year&tx_calendarize_calendar[controller]=Calendar&tx_calendarize_calendar[year]=2022), all events are shown in this year (in the above plugin with mode List), instead of current month only.

Is this a normal behaviour (can I have somehow how I want?) or is it a bug?

Thanks

**Comment by lochmueller** [comment]
Hey @GeorgeTodea ,

this is the normal behavior. As you can see in the query params only the year is set (and no month). All plugins listen to the arguments and that is the reason, that you see the complete year. If you want to change this behavior you have to adapt the year plugin and add a "month" query parameter to the year links (if there is no month in this view, you could the current month via a date function). Then you switch the year and fix the list to display just one month. But you need also a month view, because only then the user could also switch the month in one year.

I will close this issue. If you have other ideas or a programmatic solution, feel free and share your thoughts.

Regards,
Tim
