### ISSUE TITLE
Some slugs are NULL in tx_calenderize_domain_model_event

### ISSUE THREAD

**Issue by sypets** [lochmueller/calendarize#732]
I have slugs with value NULL of events which were created between 2022-03-21 and  2022-05-12. I assume there was a problem either related to calendarize or otherwise (which has since been fixed).

` select uid,pid,slug,FROM_UNIXTIME(tstamp),FROM_UNIXTIME(crdate),title from tx_calendarize_domain_model_event where not hidden and not deleted and slug is null order by crdate;`

118 rows

(I checked for news as well and there are no records with path_segment = NULL).

It might be helpful here to either have

* upgrade wizard which fixes
* command which fixes it.

I am not sure what is the best solution here, if that should be done in this extension, as separate extension or as core solution. 

## Related

* #635

**Comment by lochmueller** [comment]
Hey @sypets 

there is already a Upgrade wizard: https://github.com/lochmueller/calendarize/blob/master/Classes/Updates/PopulateEventSlugs.php you can execute the upgrade again. The generation of the slug is the TYPO3 default configuration: https://github.com/lochmueller/calendarize/blob/master/Configuration/TCA/tx_calendarize_domain_model_event.php#L89 so EX:calendarize do not create the slug, it is the DataHandler. Perhaps the Events are generated with plain SQL Scripts and not with the backend? Perhaps this would result in empty slugs.

I will close this issue, because this should not be a problem in the current Version of EXT:calendarize.

Regards,
Tim
