### ISSUE TITLE
month view links to previous and next month don't work

### ISSUE THREAD

**Issue by averlon** [lochmueller/calendarize#736]
Hi,
I am trying to get calendarize to work on my testsite.
All fine so far!
When showing the month view (template: Month.html) the links for "<" and ">" beside the month name don't work.
The link exists and if I copy the link into a new browser window it works.
But clicking on the link ("<" or ">") does not create any action.

Any idea what the reason could be?

By the way: same is with year-view!

Regards Karl-Heinz

`lochmueller/calendarize                    12.4.4   Create a structure for timely controlled tables (e.g. events) and one plugin ...`
T3 11.5

**Comment by lochmueller** [comment]
Hey @averlon 
sounds strange. Perhaps some JavaScript block the click event?! Do you use the search (result or search) on the same page?
Regards,
Tim

**Comment by averlon** [comment]
Hi @lochmueller ,
no, I don't use search. I am at the start to setup the extension. So search was not in my scope so far.

**Comment by averlon** [comment]
The link for next month is like this (in view Month.html):
http://www.t3test.loc/t3test-kalender/t3test-kalender-monat?tx_calendarize_calendar%5Baction%5D=month&tx_calendarize_calendar%5Bcontroller%5D=Calendar&tx_calendarize_calendar%5Bmonth%5D=3&tx_calendarize_calendar%5Byear%5D=2023&cHash=92ea9450ed88186cca41f8d3750490ce#c27

Not sure if JavaScript is needed?

**Comment by lochmueller** [comment]
No, you do not need JS. I asked for the search, because the pagination of the search handle some links via JS. But then this is not the reason. Link looks good. I suggest to load the RouteEnchancer configuration from the extension: https://github.com/lochmueller/calendarize/blob/master/Documentation/AdministratorManual/UrlRewrite/Index.rst#exemplary--standard-configuration then the URls should also looks nice.
Perhaps some of your Javascript handle the click event?
Regards,
Tim

**Comment by averlon** [comment]
I have used now Edge - same problem.
I have used my mobile phone - same problem.

**Comment by averlon** [comment]
from my poing of view this lik opens the same page without updating the content.

**Comment by averlon** [comment]
OK found something. But since I am not a programmer, I am not sure on that.

In partial Month.html. If I delete:
` section="c{contentObject.uid}"`
Then it works!

**Comment by lochmueller** [comment]
But then the link is wrong. That means that you are already on the page?

**Comment by averlon** [comment]
Yes, sure.
I don't see another way to do it.
You need to be on the Year page to go forward or back.
You need to be on the Month page to go forward or back.

I don't see another way!

You can have a look at www.averlon.de
Here I implemented an adjusted template for Year with an adjusted partial for Month (MonthYear.html).
And an adjusted template for Month.html

I will work today on some Details.

**Comment by lochmueller** [comment]
Hey @averlon Thanks for your support. I received your credits :)

**Comment by itx-stefanie-doell** [comment]
Hey,
I had the same issue and removing the anchor part of the link solved the problem for me as well. It makes sense why it's not working - the browser recognizes that you are already on the correct page (although some parameters are different), finds an anchor link and uses its default anchor-link-hebavior, which is scrolling to the element instead of reloading the page.

**Comment by lochmueller** [comment]
Hmm.... the parameter should changed and so, it is technical not the same site. Perhaps the routing configuration solve this problem also in a better way.

Please send this information:
- URL of the page you are
- URL of the target page, that is not working right
- Plugin configuration (monthPid?)

Regards,
Tim

**Comment by the-andyman** [comment]
This does not work for me either. But only if I use the supplied routing configuration. 
If I comment out the following two lines as a test, then the next / prev month links work.

```
# - routePath: '/{calendarize_month_label}/{year}/{month}'
# _controller: 'Calendar::month'
```

Could this be the problem?

Tested it with and without the anchor part of the link and this doesnt seem to be the problem. At least not for me.

**Comment by lochmueller** [comment]
Hey everyone,

I double check this in my v12 env with the current version.
I load the wouring configuration in my site via 
```
imports:
  - { resource: "EXT:calendarize/Configuration/Yaml/RouteEnhancers.yaml" }
 ```
Then I got clean URLs like `month/2024/6#c14` and `month/2024/7#c14`...
Without Routing configuration I got the same problem. But opening the link in a new Tab works great and I am not on the same site as the target URI (so the anchor is not the problem). BUT... I tested the extension in a bootstrap package installation and I found out, that `EXT:bootstrap_package/Resources/Public/JavaScript/Dist/bootstrap.smoothscroll.min.js` is the problem. There are "event listener" in links with anchor that are not compatible or has any problems... So I close this issue, because the Markup is not wrong and the javascript has the problem. I think something like that is also the problem on your pages...

Regards,
Tim
