### ISSUE TITLE
year view extends page width

### ISSUE THREAD

**Issue by averlon** [lochmueller/calendarize#738]
in year view there are fix tree months in one row.

If there are several events in each months, the row extends the page with.

You can currently see this at www.averlon.de/gw-kalender/

When e.g. switching to the next year, you can see it is O.K. again (less events).

Is there any way to reduce the number of months per line in year view (not by programming)?

**Comment by lochmueller** [comment]
Hey @averlon 
you can adapt this template and drop this line: https://github.com/lochmueller/calendarize/blob/master/Resources/Private/Templates/Calendar/Year.html#L39 and change the <tr><td> structure. Other conceptional solution is, to remove the detailPid from the plugin and link to a day-View.

I will close this issue. I suggest asking general integration questions in TYPO3 slack #ext-calendarize instead of creating Github issues.

Regards,
Tim
