### ISSUE TITLE
CoolURI

### ISSUE THREAD

**Issue by Hobokens** [lochmueller/calendarize#74]
Hi,
I try to shorten the url with cooluri. 

The pagination is easy:
`<part>`
	`<parameter>tx_calendarize_calendar[@widget_0][currentPage]</parameter>`
	`<t3conv>1</t3conv>`
`</part>`

But I can't find a way to get the title of the event for the detail view url. This what I tried:

`<part>`
`<parameter>tx_calendarize_calendar[index]</parameter>`
			`<lookindb>`
				`<to>SELECT path_segment,title FROM tx_calendarize_domain_model_event WHERE (uid=$1 or l10n_parent=$1) AND sys_language_uid={L=0}</to>`
			`<t3conv>1</t3conv>`
			`</lookindb>`
`</part>`
Instead of the title I only get a number.
Maybe you have a hint?

Regards
Hobokens

**Comment by lochmueller** [comment]
Hey @Hobokens ,

this is not possible by selecting the index table, because there is a "index"-ID in the URI and you need the title of the event table. For RealURL we use this userFunction:
https://github.com/lochmueller/calendarize/blob/master/Classes/UserFunction/RealurlAlias.php#L88

To build a userFunction is the beast way, to support different event tables. If you are using just the default events, this query help to reach your goal:

SELECT evt.title,idx.start_date,idx.end_time FROM tx_calendarize_domain_model_event evt,tx_calendarize_domain_model_index idx
WHERE idx.uid = $1 AND idx.foreign_uid = evt.uid;

Note: Please build a combination of the title,startdate and starttime like here:
https://github.com/lochmueller/calendarize/blob/master/Classes/UserFunction/RealurlAlias.php#L88
... to support als frequences and recurrence events without conflict.

If you finish your configuration please share the results. I will integrate same information in the upcomming documentation.

Regards,
Tim

**Comment by lochmueller** [comment]
Hey @Hobokens 
I add a method to the current git master and also add the documentation:
https://github.com/lochmueller/calendarize/blob/master/Documentation/AdministratorManual/UrlRewrite/Index.rst

If you are interested in supporting the development of the calendarize feel free to sponsor time or money ;)

Regards,
Tim
