### ISSUE TITLE
ICS Import with custom fields

### ISSUE THREAD

**Issue by x7dani** [lochmueller/calendarize#745]
I'd like to modify the ICS import to have some additional custom values (like OpenEndTime or maybe image-url) OR any possibility to add a custom event from a MySQL/PHP source.

Can you give me some hints on which parts I have to edit since I'm not experienced with TYPO3 extensions. The tutorials which can be found online seem mostly outdated.

Thank you very much in advance!!!

I can see that most stuff might have to be changed here "calendarize/Classes/Ical/" and I tried to get openEndTime working since there's already an entry which seems to be prepared, but it failed and I don't know why (no error shown in TYPO3 log, nor in PHP logs).

The ICS-file for import looks like this...

`
BEGIN:VCALENDAR
VERSION:2.0
PRODID:PHP
METHOD:PUBLISH
X-WR-CALNAME:Events
X-WR-TIMEZONE:Europe/Berlin
BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU
TZNAME:CEST
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU
TZNAME:CET
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
DTSTART;TZID=Europe/Berlin:20230512T200000
allDay : false
openEndTime : true
DTSTAMP:20230509T101336Z
LOCATION:Bürgersaal
DESCRIPTION:
SUMMARY:Programm Titel
UID:19ca14e7ea6328a42e0eb13d585e4c22
SEQUENCE:0
END:VEVENT
BEGIN:VEVENT
DTSTART;TZID=Europe/Berlin:20230513T200000
allDay : false
openEndTime : true
DTSTAMP:20230509T101336Z
LOCATION:Location
DESCRIPTION:
SUMMARY:Programm Titel
UID:a5771bce93e200c36f7cd9dfd0e5deaa
SEQUENCE:0
END:VEVENT
END:VCALENDAR
`

calendarize/Classes/Ical/DissectEventAdapter.php
changed "return false" to "return true" in line 174

`
    public function isOpenEndTime(): bool
    {
        return true;
    }
`

PS: The import works of course, but the endtime is 23:00 and not "openEndTime". :-)

**Comment by lochmueller** [comment]
Hey @x7dani 

do you install the extension with composer? The "DissectICal" stuff is only a fallback for non-composer installations. I suggest to manage your installation with composer. In this case the extension handle the import stuff with "sabre/vobject" wich is much better. You could also implement the "ICalServiceInterface" interface and handle the import in your way (don't forget to set your class as alias for the interface in the DI container). I think this is the easiest way. There is also a PSR event in the Import process ("ImportSingleIcalEvent"), but you have to check, if this is to late to fit your requirements. Your base problem is, that "hydrateCalendarize" do not call "setOpenEndTime" because there is no concept for "open end" in ICS context.

I hope my ideas are useful for your solution?!

Regards,
Tim

**Comment by x7dani** [comment]
Hey Tim, thank you for your advice and insight.
Honestly I'm not smart nor experienced enough to fully understand your solution, but thank you very much for your help anyways.
I also took a look at the extension external_import (https://extensions.typo3.org/extension/external_import), but I don't want to mess up the data stored in the tables.

Still, great work on calendarize!! :D

**Comment by lochmueller** [comment]
I close this issue. The integration ist very old (2016). It is recommended to use the extension in composer mode to get modern ical libs for ICS parsing.
