### ISSUE TITLE
Incorrect date time format in ics

### ISSUE THREAD

**Issue by cundd** [lochmueller/calendarize#77]
I think the format of the date time in the ics is incorrect (https://github.com/lochmueller/calendarize/blob/master/Resources/Private/Partials/Feed/Item.ics#L4-5).

If I understand correctly, [RFC5545](https://tools.ietf.org/html/rfc5545#section-3.3.5) says that the time zone must not appended.

I recognized this, because the event didn't show up in Calendar on OS X.

**Comment by lochmueller** [comment]
Thanks for the report. There was wrong "%" in front of the "Z". Now the format is "RFC5545" incl. the "Z" for UTC.

**Comment by cundd** [comment]
Thank you for having a look! But is UTC the right timezone to use? I think I got a 2 hour offset when I tried it. Or may this be a problem of my TYPO3 installation?

**Comment by lochmueller** [comment]
I think it is a problem of the installation. Furthermore I think UTC is default since CMS 8.x, so UTC should also the default in the template. If you want to change the timezone, you can overwrite the template and use form 3: TZID=America/New_York:19980119T020000

If you cannot change the behaviour, need same help or think it is still a bug, please create a new issue...

**Comment by cundd** [comment]
I'll do that if needed. :)

Thank you for your help
