### ISSUE TITLE
Add support for typo3 categories

### ISSUE THREAD

**Issue by mvoehringer** [lochmueller/calendarize#9]
It would be nice to have the option to limit the output to a subset of events at once. One way would be the support of different sys-folder (see #7) or to have the option to select an category of events to show.

**Comment by lochmueller** [comment]
#7 would by fixed in the next day. A category selection should be not part of the calendarize extension itself, because it is part of the event structure. Calendarize try to be independant of the event structure... there are slots to reduce the selection of events.... but your are right... a option is missing, that external integration can add the selection (e.g. categories) in the flexform configuration...

**Comment by mvoehringer** [comment]
I understand why you don't want to integrate the category into calendarize. An option to add such an selection by my own extension would be great. 

Michael

**Comment by lochmueller** [comment]
Hey Michael,

I add the feature in the current master. The category selection (example with the default Event Model) is part of the next release...

Regards,
Tim
